config/routes.rb
SocialListening::Application.routes.draw do
  
  resources :insights

  resources :profiles

  resources :checkins

  scope module: 'clients' do
    resources :foursquare_clients, only: ['new'], path: 'clients/foursquare' do
      collection do
        get 'callback'
      end
    end
    resources :facebook_clients, only: ['new'], path: 'clients/facebook' do
      collection do
        get 'callback'
      end
    end
    resources :instagram_clients, only: ['new'], path: 'clients/instagram' do
      collection do
        get 'callback'
      end
    end
    resources :twitter_clients, only: ['new'], path: 'clients/twitter' do
      collection do
        get 'callback'
      end
    end
  end

  devise_for :users

  resources :attributes

  root :to => "page#index"
  match "/about" => "page#about"

  match "/profile" => "profile#index"
  match "/stat" => "stat#index"

  post '/realtime/foursquare' => 'realtime#foursquare'

  post '/realtime/instagram' => 'realtime#instagram'
  get '/realtime/instagram' => 'realtime#instagramVerify'

  post '/realtime/facebook' => 'realtime#facebook'
  get '/realtime/facebook' => 'realtime#facebookVerify'

end

app/models/insight.rb
class Insight < ActiveRecord::Base
  attr_accessible :Page, :page_engaged_users, :page_fan_adds, :page_places_checkins, :page_posts_impressions, :page_views
end

app/controllers/insights_controller.rb
class InsightsController < ApplicationController
  # GET /insights
  # GET /insights.json
  def index
    @insights = Insight.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @insights }
    end
  end

  # GET /insights/1
  # GET /insights/1.json
  def show
    @insight = Insight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @insight }
    end
  end

  # GET /insights/new
  # GET /insights/new.json
  def new
    @insight = Insight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @insight }
    end
  end

  # GET /insights/1/edit
  def edit
    @insight = Insight.find(params[:id])
  end

  # POST /insights
  # POST /insights.json
  def create
    @insight = Insight.new(params[:insight])

    respond_to do |format|
      if @insight.save
        format.html { redirect_to @insight, notice: 'Insight was successfully created.' }
        format.json { render json: @insight, status: :created, location: @insight }
      else
        format.html { render action: "new" }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /insights/1
  # PUT /insights/1.json
  def update
    @insight = Insight.find(params[:id])

    respond_to do |format|
      if @insight.update_attributes(params[:insight])
        format.html { redirect_to @insight, notice: 'Insight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insights/1
  # DELETE /insights/1.json
  def destroy
    @insight = Insight.find(params[:id])
    @insight.destroy

    respond_to do |format|
      format.html { redirect_to insights_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/views/insights/_form.html.erb
<%= form_for @insight, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :Page, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Page, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :page_fan_adds, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :page_fan_adds, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :page_views, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :page_views, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :page_engaged_users, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :page_engaged_users, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :page_places_checkins, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :page_places_checkins, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :page_posts_impressions, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :page_posts_impressions, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                insights_path, :class => 'btn' %>
  </div>
<% end %>

app/views/insights/edit.html.erb
<%- model_class = Insight -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/insights/index.html.erb
<%- model_class = Insight -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Page) %></th>
      <th><%= model_class.human_attribute_name(:page_fan_adds) %></th>
      <th><%= model_class.human_attribute_name(:page_views) %></th>
      <th><%= model_class.human_attribute_name(:page_engaged_users) %></th>
      <th><%= model_class.human_attribute_name(:page_places_checkins) %></th>
      <th><%= model_class.human_attribute_name(:page_posts_impressions) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @insights.each do |insight| %>
      <tr>
        <td><%= link_to insight.id, insight_path(insight) %></td>
        <td><%= insight.Page %></td>
        <td><%= insight.page_fan_adds %></td>
        <td><%= insight.page_views %></td>
        <td><%= insight.page_engaged_users %></td>
        <td><%= insight.page_places_checkins %></td>
        <td><%= insight.page_posts_impressions %></td>
        <td><%=l insight.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_insight_path(insight), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      insight_path(insight),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_insight_path,
            :class => 'btn btn-primary' %>

app/views/insights/new.html.erb
<%- model_class = Insight -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/insights/show.html.erb
<%- model_class = Insight -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Page) %>:</strong></dt>
  <dd><%= @insight.Page %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page_fan_adds) %>:</strong></dt>
  <dd><%= @insight.page_fan_adds %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page_views) %>:</strong></dt>
  <dd><%= @insight.page_views %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page_engaged_users) %>:</strong></dt>
  <dd><%= @insight.page_engaged_users %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page_places_checkins) %>:</strong></dt>
  <dd><%= @insight.page_places_checkins %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page_posts_impressions) %>:</strong></dt>
  <dd><%= @insight.page_posts_impressions %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              insights_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_insight_path(@insight), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              insight_path(@insight),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>