config/routes.rb
SocialListening::Application.routes.draw do
  
  resources :insights

  resources :profiles

  resources :checkins

  scope module: 'clients' do
    resources :foursquare_clients, only: ['new'], path: 'clients/foursquare' do
      collection do
        get 'callback'
      end
    end
    resources :facebook_clients, only: ['new'], path: 'clients/facebook' do
      collection do
        get 'callback'
      end
    end
    resources :instagram_clients, only: ['new'], path: 'clients/instagram' do
      collection do
        get 'callback'
      end
    end
    resources :twitter_clients, only: ['new'], path: 'clients/twitter' do
      collection do
        get 'callback'
      end
    end
  end

  devise_for :users

  resources :attributes

  root :to => "page#index"
  match "/about" => "page#about"

  match "/profile" => "profile#index"
  match "/stat" => "stat#index"

  post '/realtime/foursquare' => 'realtime#foursquare'

  post '/realtime/instagram' => 'realtime#instagram'
  get '/realtime/instagram' => 'realtime#instagramVerify'

  post '/realtime/facebook' => 'realtime#facebook'
  get '/realtime/facebook' => 'realtime#facebookVerify'

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  attr_accessible :created_at, :rm_service_id, :rm_merchant_id, 
    :rm_user_id, 
    :rm_created_at, 
    :rm_message_id,
    :rm_message_url,
    :user_first_name,
    :user_last_name,
    :user_screen_name,
    :user_photo_url,
    :user_info, 
    :post_text, 
    :post_url, 
    :picture, 
    :location, 
    :place_id, 
    :notes, 
    :message, 
    :client_id 

    belongs_to :profile

end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  #skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!

  def index
    @checkins = Checkin.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkins }
    end
  end
  
  def edit
    @checkin = Checkin.find(params[:id])
  end

  def show
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkin }
    end
  end
  def update
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      if @checkin.update_attributes(params[:checkin])
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json do
          head :no_content
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

def destroy
    @checkin = Checkin.find(params[:id])
    @checkin.destroy

    respond_to do |format|
      format.html { redirect_to checkins_url }
      format.json { head :no_content }
    end
  end
end

app/views/checkins/_form.html.erb
<%= form_for @checkin, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rm_user_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :notes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :notes, :class => 'text_field' %>
    </div>
  </div>

   <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    
  </div>
<% end %>

app/views/checkins/edit.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/checkins/index.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1>Social Check-ins</h1> <a href="/checkins"><img src="/assets/refresh.png" /></a>
</div>


<% @checkins.each do |checkin| %>
    <div class="checkIn <%= checkin.rm_service_id %>">
        <div class="profilePic">
          <img src="<%= checkin.user_photo %>" />
        </div><div class="profileContent">
          <ul>
            <li class="name"><img src="/assets/<%= checkin.rm_service_id %>.png" /><%= checkin.user_first_name %> <%= checkin.user_last_name %> <span class="addNote <%= checkin.id %>">Add Note</span></li>
            <li class="message">
              <a href="<%= checkin.rm_message_url %>" target="_blank">
                <%= checkin.post_text %>
              </a>
                <div class="time">
                  <%= checkin.created_at.strftime("- %m/%d/%Y")%>
                </div>
               
            
              <input type="hidden" id="checkinId" value="<%= checkin.id %>" />
              <!--<td><%= checkin.notes%></td> -->
             
              
            <form class="addNoteForm" id="edit_checkin_<%= checkin.id %>" action="/checkins/<%= checkin.id %>">
              <input type="textarea" name="checkin_notes" id="checkin_notes" />
              <input type="hidden" id="checkin_rm_user_id" value="<%= checkin.rm_user_id %>" />
              <input type="submit" value="Add Note" />
            </form>
          </ul>
        </div>
      </div>
<% end %>


<table class="table table-striped">
  <thead>
    <tr>
    
      <th><%= model_class.human_attribute_name(:name) %></th>
 
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= link_to checkin.id, checkin_path(checkin) %></td>
        <td><%= checkin.rm_user_id %></td>
        <td><%= checkin.user_first_name %></td>
        <td><%= checkin.user_last_name %></td>
      
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_checkin_path(checkin), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      checkin_path(checkin),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
$('.addNote').click(function(){
  checkinId = $(this).attr('class').split(" ")[1];

  $("#edit_checkin_"+checkinId).toggle();
  $("#edit_checkin_"+checkinId+" #checkin_notes").focus()

  /*
    $(form).on('submit', function(e) {
      e.preventDefault();
      var data = $(form).serialize()
      $post(
          url: "/checkins/#{id}",
          params: data,
          success: function(e) {
            // Show success, or embed the data into view
          }
        )
    })*/
});

</script>

app/views/checkins/show.html.erb
<%- model_class = Checkin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rm_user_id) %>:</strong></dt>
  <dd><%= @checkin.rm_user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_first_name) %>:</strong></dt>
  <dd><%= @checkin.user_first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_last_name) %>:</strong></dt>
  <dd><%= @checkin.user_last_name %></dd>
  
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              checkins_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_checkin_path(@checkin), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              checkin_path(@checkin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>