config/routes.rb
SocialListening::Application.routes.draw do
  
  resources :insights

  resources :profiles

  resources :checkins

  scope module: 'clients' do
    resources :foursquare_clients, only: ['new'], path: 'clients/foursquare' do
      collection do
        get 'callback'
      end
    end
    resources :facebook_clients, only: ['new'], path: 'clients/facebook' do
      collection do
        get 'callback'
      end
    end
    resources :instagram_clients, only: ['new'], path: 'clients/instagram' do
      collection do
        get 'callback'
      end
    end
    resources :twitter_clients, only: ['new'], path: 'clients/twitter' do
      collection do
        get 'callback'
      end
    end
  end

  devise_for :users

  resources :attributes

  root :to => "page#index"
  match "/about" => "page#about"

  match "/profile" => "profile#index"
  match "/stat" => "stat#index"

  post '/realtime/foursquare' => 'realtime#foursquare'

  post '/realtime/instagram' => 'realtime#instagram'
  get '/realtime/instagram' => 'realtime#instagramVerify'

  post '/realtime/facebook' => 'realtime#facebook'
  get '/realtime/facebook' => 'realtime#facebookVerify'

end

app/views/layouts/_message.html.erb
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <title><%= content_for?(:title) ? yield(:title) : "Social Listening" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"></a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><a href="/">Home</a>
                <li><%= link_to "Checkins", checkins_path %></li>
                <li><%= link_to "Settings", profiles_path %></li>
                <!--<li><%= link_to "Edit Account", edit_user_registration_path %></li>
                 <li><%= link_to "Statistics", stat_path %></li> -->
                <li><%= link_to "Logout", destroy_user_session_path, method: "DELETE" %></li>

              <% else -%>
                <li><%= link_to "Login", new_user_session_path %>
                <li><%= link_to "Signup", new_user_registration_path %>
              <% end -%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="span12 logo">
      <img src="/assets/logo.png" />
    </div>

    <div class="container">
      <div class="content">
        
        <div class="row">
           <div class="span12 mainContent">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>